name: Playwright Table Scraper

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Playwright for 23f2003233@ds.study.iitm.ac.in
        run: |
          npm init -y
          npm install playwright
          npx playwright install chromium --with-deps

      - name: Run Scraper
        run: node scraper.js
